<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>DarksCustoms</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/*.xaml.cs;**/*.xaml</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\NINA.Plugin\NINA.Plugin.csproj" />
    <ProjectReference Include="..\..\..\..\System.Windows.Compat\System.Windows.Compat.csproj" />
    <PackageReference Include="System.Drawing.Common" Version="*" ExcludeAssets="all" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ReachFramework" />
    <Reference Include="System.Net" />
    <Reference Include="System.Printing" />
    <Reference Include="System.Windows" />
  </ItemGroup>
  <Target Name="PostBuildLinux" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir -p $HOME/.local/share/NINA/Plugins/3.0.0/DarkCustoms" />
    <Exec Command="cp $(TargetPath) $HOME/.local/share/NINA/Plugins/3.0.0/DarkCustoms/" />
  </Target>
</Project>
